### PR TITLE
remove laminas/laminas-dependency-plugin requirement

### PR DESCRIPTION
**Pull request by samsonasik**
laminas/laminas-dependency-plugin should only used in project.

### CODE REVIEW

**Comment by vincequeiroz** [comment]
It'll me possible remove this dependency?

**Comment by snapshotpl** [comment]
@vincequeiroz yes, its required as migration tool

**Comment by Saeven** [comment]
Thanks for this PR @samsonasik 

Yes, please remove this or at least upgrade it to ^2.2.0.  Causing a number of issues.

**Comment by jarrettj** [comment]
+1

**Comment by vincequeiroz** [comment]
Could you help us, @howardlopez?

**Comment by davidwindell** [comment]
Please can someone merge this?

**Comment by Saeven** [comment]
@davidwindell not sure if this helps you, but I needed this for a Laminas project - forked and submitted to packagist: https://packagist.org/packages/saeven/laminas-aws-sdk

**Comment by jarrettj** [comment]
Been over a year 🤷🏾‍♂️

**Comment by davidwindell** [comment]
Thanks @Saeven, appreciate that, will switch to your fork. I guess AWS have abandoned this repo now.

**Comment by stobrien89** [comment]
Hi all, 

Apologies for the delay. I agree that this should probably be used at the project level.  I'll merge and cut another release.

**Comment by jarrettj** [comment]
Yay! Thanks @stobrien89. Much appreciated. Maybe we as a community can also help if needed. Especially since we have apps depending on this module :)

**Comment by davidwindell** [comment]
@stobrien89 thanks however we can't use the module without the fork from @Saeven until PHP 8 support is added, is there any plans for that?

**Pull request merged**
