### PR TITLE
Zf sm3 compatibility

### PR DESCRIPTION
**Pull request by basz**
Adds factory compatibility for zend-servicemanager 3

Note minimum requirement is now ^2.7 which might need to be reflected in composer

### CODE REVIEW

**Comment by cjyclaire** [comment]
Looks good to me, I'll double check with @jeremeamia who has more expertise in zf, does this looks good to you?

**Comment by basz** [comment]
soft ping

**Comment by cjyclaire** [comment]
LGTM, :shipit:

**Comment by bakura10** [comment]
Would it be possible to tag this? :)

**Comment by cjyclaire** [comment]
Tagged! Thanks for the reminder :)

**Comment by bakura10** [comment]
Thanks! ping @basz ;)

**Comment by basz** [comment]
thanks

**Comment by cjyclaire** [comment]
Apology for changing the tag. Version Tag has been changed to a minor version, since this could be breaking change for customer using 2.0.x.

**Comment by basz** [comment]
not a problem. thanks again

**Comment by mikel5** [comment]
The change to AwsModule\Factory\AwsFactory is now incompatible with ZF2.   The Service Manager in ZF2 isn't an instance of Interop\Container\ContainerInterface

**Comment by cjyclaire** [comment]
Ping here, composer dependency is fixed, and a new release is tagged, apology for tag changing.

**Pull request merged**
